"""
Django settings for dioeDB project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOGIN_URL = 'dioedb_login'
LOGOUT_URL = 'dioedb_logout'
LOGIN_REDIRECT_URL = 'Startseite:start'
CRISPY_TEMPLATE_PACK = 'bootstrap3'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5@l-y9u7y_7plh(7xq2u-_ilgushpm*&^7&j0%6o-(b0&d31bj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'Startseite',
	'PersonenDB',
	'KorpusDB',
	'DB',
	'crispy_forms',
)

MIDDLEWARE_CLASSES = (
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'dioeDB.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'dioeDB', 'templates'),os.path.join(BASE_DIR, 'Startseite', 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'dioeDB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# DIOEDB_DB="django.db.backends.postgresql"
# DIOEDB_DB_NAME="PersonenDB"
# DIOEDB_DB_USER="user"
# DIOEDB_DB_PASSWORD="passwort"
# DIOEDB_DB_HOST="postgresql://localhost"
# DIOEDB_DB_PORT="5433"

if 'DIOEDB_DB' in os.environ and os.environ['DIOEDB_DB']:
	DATABASES['default']['ENGINE'] = os.environ['DIOEDB_DB']
	if 'DIOEDB_DB' in os.environ['DIOEDB_DB_NAME']:
		DATABASES['default']['NAME'] = os.environ['DIOEDB_DB_NAME']
	if 'DIOEDB_DB' in os.environ['DIOEDB_DB_USER']:
		DATABASES['default']['USER'] = os.environ['DIOEDB_DB_USER']
	if 'DIOEDB_DB' in os.environ['DIOEDB_DB_PASSWORD']:
		DATABASES['default']['PASSWORD'] = os.environ['DIOEDB_DB_PASSWORD']
	if 'DIOEDB_DB' in os.environ['DIOEDB_DB_HOST']:
		DATABASES['default']['HOST'] = os.environ['DIOEDB_DB_HOST']
	if 'DIOEDB_DB' in os.environ['DIOEDB_DB_PORT']:
		DATABASES['default']['PORT'] = os.environ['DIOEDB_DB_PORT']
else:
	DATABASES = {
		'default': {
			'ENGINE': 'django.db.backends.sqlite3',
			'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
		}
	}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'de-DE'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = False
USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
	os.path.join(BASE_DIR, 'dioeDB', 'static'),
	os.path.join(BASE_DIR, 'DB', 'static'),
	os.path.join(BASE_DIR, 'KorpusDB', 'static'),
)
